In [1]:
import pandas as pd

In [8]:
pwd

'C:\\Users\\Maria O Sullivan\\Desktop\\assginment 2 programming\\Programming-for-data-analysis-project'

In [17]:
df = pd.read_csv("Toddler Autism dataset July 2018.csv")

In [18]:
# read file
df

,Unnamed: 0,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,Age_Mons,Qchat-10-Score,Sex,Ethnicity,Jaundice,Family_mem_with_ASD,Who completed the test,Class/ASD Traits
0,1,0,0,0,0,0,0,1,1,0,1,28,3,f,middle eastern,yes,no,family member,No
1,2,1,1,0,0,0,1,1,0,0,0,36,4,m,White European,yes,no,family member,Yes
2,3,1,0,0,0,0,0,1,1,0,1,36,4,m,middle eastern,yes,no,family member,Yes
3,4,1,1,1,1,1,1,1,1,1,1,24,10,m,Hispanic,no,no,family member,Yes
4,5,1,1,0,1,1,1,1,1,1,1,20,9,f,White European,no,yes,family member,Yes
5,6,1,1,0,0,1,1,1,1,1,1,21,8,m,black,no,no,family member,Yes
6,7,1,0,0,1,1,1,0,0,1,0,33,5,m,asian,yes,no,family member,Yes
7,8,0,1,0,0,1,0,1,1,1,1,33,6,m,asian,yes,no,family member,Yes
8,9,0,0,0,0,0,0,1,0,0,1,36,2,m,asian,no,no,family member,No
9,10,1,1,1,0,1,1,0,1,1,1,22,8,m,south asian,no,no,Health Care Professional,Yes
10,11,1,0,0,1,0,1,1,0,1,1,36,6,m,Hispanic,yes,yes,family member,Yes
11,12,1,1,1,1,0,1,1,1,0,1,17,8,m,middle eastern,yes,no,family member,Yes
12,13,0,0,0,0,0,0,0,0,0,0,25,0,f,middle eastern,yes,no,family member,No
13,14,1,1,1,1,0,0,1,0,1,1,15,7,f,middle eastern,yes,no,family member,Yes
14,15,0,0,0,0,0,0,0,0,0,0,18,0,m,middle eastern,no,no,family member,No
15,16,1,1,1,0,1,0,1,1,0,1,12,7,m,black,no,no,family member,Yes
16,17,0,0,0,0,0,0,0,0,0,0,36,0,m,middle eastern,no,yes,family member,No
17,18,1,1,1,0,1,1,1,1,0,1,12,8,f,middle eastern,yes,no,family member,Yes
18,19,1,0,0,0,1,0,0,0,0,1,29,3,f,middle eastern,no,no,family member,No
19,20,1,1,1,0,1,0,1,1,0,1,12,7,f,black,no,no,family member,Yes
20,21,1,0,0,1,1,1,1,1,1,0,36,7,m,middle eastern,no,no,family member,Yes
21,22,1,0,1,1,1,1,1,0,1,0,36,7,m,middle eastern,no,no,family member,Yes
22,23,1,0,1,1,0,1,0,1,1,1,36,7,m,Native Indian,yes,yes,Health Care Professional,Yes
23,24,1,1,1,0,1,1,0,1,1,0,36,7,m,middle eastern,yes,yes,family member,Yes
24,25,1,1,1,1,1,1,1,1,1,0,22,9,m,White European,no,no,family member,Yes
25,26,0,0,0,0,0,0,0,0,0,0,24,0,f,middle eastern,no,no,family member,No
26,27,1,1,0,1,1,1,1,1,0,1,36,8,m,middle eastern,no,no,family member,Yes
27,28,1,1,1,1,1,1,1,1,1,1,35,10,m,Others,yes,no,family member,Yes
28,29,0,0,1,1,1,0,1,1,1,1,36,7,m,middle eastern,no,yes,family member,Yes
29,30,0,0,0,0,0,0,0,0,0,0,32,0,m,middle eastern,yes,no,family member,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1024,1025,0,0,0,0,0,0,0,0,0,1,35,1,m,asian,yes,no,family member,No
1025,1026,0,0,0,0,0,0,1,1,0,1,23,3,m,asian,yes,no,family member,No
1026,1027,0,0,0,0,0,0,0,0,0,1,36,1,m,White European,no,no,family member,No
1027,1028,0,0,1,1,1,0,0,1,1,0,29,5,m,White European,no,no,family member,Yes
1028,1029,0,0,1,1,1,1,0,0,1,0,22,5,f,Latino,no,no,family member,Yes
1029,1030,1,1,0,1,0,1,1,1,1,1,36,8,m,White European,no,yes,family member,Yes
1030,1031,0,0,0,0,1,0,0,1,0,1,36,3,m,south asian,yes,no,family member,No
1031,1032,1,1,0,0,0,1,1,1,0,1,36,6,f,Others,no,yes,family member,Yes
1032,1033,1,0,1,1,1,0,1,0,0,0,32,5,m,White European,yes,no,family member,Yes
1033,1034,0,0,0,0,0,1,0,0,0,1,16,2,m,south asian,yes,yes,Health Care Professional,No
1034,1035,0,0,0,0,0,0,0,1,0,0,28,1,m,White European,no,no,family member,No
1035,1036,1,0,0,1,0,1,1,1,0,0,18,5,m,Others,yes,no,family member,Yes
1036,1037,1,1,0,1,0,1,1,1,0,0,14,6,f,asian,no,no,family member,Yes
1037,1038,0,0,1,0,0,0,0,0,0,0,12,1,m,White European,no,no,family member,No
1038,1039,1,1,0,0,0,0,1,0,1,0,26,4,m,asian,no,yes,family member,Yes
1039,1040,0,0,0,0,1,1,1,0,1,0,26,4,m,asian,no,yes,family member,Yes
1040,1041,0,0,0,0,0,0,0,0,0,1,25,1,m,White European,no,no,family member,No
1041,1042,0,0,0,1,0,0,1,0,0,0,25,2,m,White European,yes,no,family member,No
1042,1043,1,1,1,1,0,0,1,1,1,1,30,8,m,Hispanic,yes,no,family member,Yes
1043,1044,1,1,1,1,1,1,1,1,1,1,25,10,m,asian,no,yes,family member,Yes
1044,1045,1,1,1,1,1,1,1,1,1,1,25,10,m,asian,no,yes,family member,Yes
1045,1046,1,1,1,1,1,1,1,1,1,1,30,10,m,middle eastern,no,no,Health Care Professional,Yes
1046,1047,0,1,0,1,1,1,1,1,1,0,24,7,f,middle eastern,no,no,family member,Yes
1047,1048,1,1,0,0,1,1,1,0,0,0,30,5,f,White European,no,no,family member,Yes
1048,1049,0,0,0,0,0,0,0,0,0,0,30,0,f,White European,no,no,family member,No
1049,1050,0,0,0,0,0,0,0,0,0,1,24,1,f,White European,no,yes,family member,No
1050,1051,0,0,1,1,1,0,1,0,1,0,12,5,m,black,yes,no,family member,Yes
1051,1052,1,0,1,1,1,1,1,1,1,1,18,9,m,middle eastern,yes,no,family member,Yes
1052,1053,1,0,0,0,0,0,0,1,0,1,19,3,m,White European,no,yes,family member,No
1053,1054,1,1,0,0,1,1,0,1,1,0,24,6,m,asian,yes,yes,family member,Yes

In [11]:
df.head()

,Unnamed: 0,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,Age_Mons,Qchat-10-Score,Sex,Ethnicity,Jaundice,Family_mem_with_ASD,Who completed the test,Class/ASD Traits
0,1,0,0,0,0,0,0,1,1,0,1,28,3,f,middle eastern,yes,no,family member,No
1,2,1,1,0,0,0,1,1,0,0,0,36,4,m,White European,yes,no,family member,Yes
2,3,1,0,0,0,0,0,1,1,0,1,36,4,m,middle eastern,yes,no,family member,Yes
3,4,1,1,1,1,1,1,1,1,1,1,24,10,m,Hispanic,no,no,family member,Yes
4,5,1,1,0,1,1,1,1,1,1,1,20,9,f,White European,no,yes,family member,Yes

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1054 entries, 0 to 1053
Data columns (total 19 columns):
Unnamed: 0                1054 non-null int64
A1                        1054 non-null int64
A2                        1054 non-null int64
A3                        1054 non-null int64
A4                        1054 non-null int64
A5                        1054 non-null int64
A6                        1054 non-null int64
A7                        1054 non-null int64
A8                        1054 non-null int64
A9                        1054 non-null int64
A10                       1054 non-null int64
Age_Mons                  1054 non-null int64
Qchat-10-Score            1054 non-null int64
Sex                       1054 non-null object
Ethnicity                 1054 non-null object
Jaundice                  1054 non-null object
Family_mem_with_ASD       1054 non-null object
Who completed the test    1054 non-null object
Class/ASD Traits          1054 non-null object
dtypes: int64(13), object(6)
memory usage: 156.5+ KB

In [13]:
df.describe()

,Unnamed: 0,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,Age_Mons,Qchat-10-Score
count,1054.000000,1054.000000,1054.000000,1054.000000,1054.000000,1054.000000,1054.000000,1054.000000,1054.000000,1054.000000,1054.000000,1054.000000,1054.000000
mean,527.500000,0.563567,0.448767,0.401328,0.512334,0.524668,0.576850,0.649905,0.459203,0.489564,0.586338,27.867173,5.212524
std,304.407895,0.496178,0.497604,0.490400,0.500085,0.499628,0.494293,0.477226,0.498569,0.500128,0.492723,7.980354,2.907304
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,12.000000,0.000000
25%,264.250000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,23.000000,3.000000
50%,527.500000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000,30.000000,5.000000
75%,790.750000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,36.000000,8.000000
max,1054.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,36.000000,10.000000

In [16]:
df.columns

Index(['Unnamed: 0', 'A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'A9',
       'A10', 'Age_Mons', 'Qchat-10-Score', 'Sex', 'Ethnicity', 'Jaundice',
       'Family_mem_with_ASD', 'Who completed the test', 'Class/ASD Traits '],
      dtype='object')